name: Deploy to Shared Hosting

on:
  push:
    branches:
      - ankit-test # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install sshpass
        run: |
          sudo apt-get install -y sshpass

      - name: scp command
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          echo "UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          sshpass -p "1c!Y3S5E!4$w" scp -r faruk@45.76.134.183:./ /home/1098524.cloudwaysapps.com/ytcatbavac/public_html/ankit-test/
